### ISSUE TITLE
当把MPickerView的高度由160dp改为180dp或更高之后，选中的位置变了

### ISSUE THREAD

**Issue by ziyouxiaozi** [jzmanu/MDatePickerSample#1]
如图
![image](https://user-images.githubusercontent.com/2511739/93413651-4f91d780-f8d2-11ea-9d1e-00b097a58359.png)

**Comment by jzmanu** [comment]
这是修改了源码导致的，mpvDialogYear在代码中也进行了设置，不能只改xml，也要在代码中同步修改。

**Comment by ziyouxiaozi** [comment]
在源码的哪个地方？

**Comment by ziyouxiaozi** [comment]
我看到了！但是为什么在源码还要再次设置呢，当支持时间选择的时候？指点一下！

**Comment by jzmanu** [comment]
因为年份是四位数，需要重新设置weight以避免地分辨率设备上显示不全的问题

**Comment by ziyouxiaozi** [comment]
了解了！

**Comment by ziyouxiaozi** [comment]
那又没有更好的办法改了xml的值在源码里面也能获取到，然后直接就用那个值呢？

**Comment by jzmanu** [comment]
肯定是可以的，但是没必要

**Comment by ziyouxiaozi** [comment]
好的！多谢
