### ISSUE TITLE
弹窗年份范围问题

### ISSUE THREAD

**Issue by westmac-water** [jzmanu/MDatePickerSample#6]
![image](https://user-images.githubusercontent.com/67319453/176391255-9938eb8f-e676-40aa-a7b1-9c9c7250e0a0.png)
我在main中换成了红框所示代码，但为什么弹窗的年份还是没变，我该如何修改调整？
然后就是第二个问题:
![image](https://user-images.githubusercontent.com/67319453/176391462-80933368-1a2c-4476-a0f5-132f0df3c917.png)
数字上方和下方的分隔线，我该如何修改，才能做到如下图片所示的这种效果？
![image](https://user-images.githubusercontent.com/67319453/176391660-2cec3d71-59b4-4122-8861-10c3cbec2541.png)

**Comment by jzmanu** [comment]
> ![image](https://user-images.githubusercontent.com/67319453/176391255-9938eb8f-e676-40aa-a7b1-9c9c7250e0a0.png) 我在main中换成了红框所示代码，但为什么弹窗的年份还是没变，我该如何修改调整？ 然后就是第二个问题: ![image](https://user-images.githubusercontent.com/67319453/176391462-80933368-1a2c-4476-a0f5-132f0df3c917.png) 数字上方和下方的分隔线，我该如何修改，才能做到如下图片所示的这种效果？ ![image](https://user-images.githubusercontent.com/67319453/176391660-2cec3d71-59b4-4122-8861-10c3cbec2541.png)

1. 要设置指定的MPickerView对象才生效。
2. 查看mPaintLine相关代码可实现的，后续有空尝试添加该功能。
